version: '3'
services:
  front-end:
    hostname: frontend
    image: dtdemos/dt-orders-frontend:1
    ports:
      - 80:8080
    environment:
      - CUSTOMER_URL=http://172.17.0.1:8181
      - CATALOG_URL=http://172.17.0.1:8182
      - ORDER_URL=http://172.17.0.1:8183
      - DT_CUSTOM_PROP=project=dt-orders stage=dev service=frontend owner=app-team-2 backend=services
      - DT_CLUSTER_ID=dev-frontend
      - DT_RELEASE_STAGE=dev
      - DT_RELEASE_PRODUCT=dt-orders-frontend
      - DT_RELEASE_VERSION=1
  customer-service:
    hostname: customer
    image: dtdemos/dt-orders-customer-service:1
    ports:
      - 8181:8080
    environment:
      - DT_CUSTOM_PROP=project=dt-orders stage=dev service=customer-service owner=app-team-1
      - DT_CLUSTER_ID=dev-customer-service
      - DT_RELEASE_STAGE=dev
      - DT_RELEASE_PRODUCT=dt-orders-customer-service
      - DT_RELEASE_VERSION=1
  catalog-service:
    hostname: catalog
    image: dtdemos/dt-orders-catalog-service:1
    ports:
      - 8182:8080
    environment:
      - DT_CUSTOM_PROP=project=dt-orders stage=dev service=catalog-service owner=app-team-1
      - DT_CLUSTER_ID=dev-catalog-service
      - DT_RELEASE_STAGE=dev
      - DT_RELEASE_PRODUCT=dt-orders-catalog-service
      - DT_RELEASE_VERSION=1
  order-service:
    hostname: order
    image: dtdemos/dt-orders-order-service:1
    ports:
      - 8183:8080
    environment:
      - CUSTOMER_SERVICE_DOMAIN=172.17.0.1
      - CUSTOMER_SERVICE_PORT=8181
      - CATALOG_SERVICE_DOMAIN=172.17.0.1
      - CATALOG_SERVICE_PORT=8182
      - DT_CUSTOM_PROP=project=dt-orders stage=dev service=order-service owner=app-team-1
      - DT_CLUSTER_ID=dev-order-service
      - DT_RELEASE_STAGE=dev
      - DT_RELEASE_PRODUCT=dt-orders-order-service
      - DT_RELEASE_VERSION=1
  order-load:
    hostname: load
    image: dtdemos/dt-orders-load:1
    environment:
      - HOSTNAME=172.17.0.1
      - SERVER_PORT=80
      - NUM_LOOPS=10000
      - NUM_THREADS=1
      - THINK_TIME=250
      - TEST_SCRIPT=load.jmx
      - TEST_DEBUG=false
    restart: always
  order-browser:
    hostname: browser
    image: dtdemos/dt-orders-browser:1
    environment:
      - APP_URL=http://172.17.0.1
      - SCRIPT_NUM_LOOPS=1000
    restart: always